### PR TITLE
Tammam/connect to api

### PR DESCRIPTION
**Pull request by 1992tw**
Connected Dashboard and Login to the backend API. 
Dashboard shows all activities now.
Login sends a req and shows a toaster message if login failed

### CODE REVIEW

**Review by vitaliipp — CHANGES_REQUESTED** [review]
Great job, but one of our mentors didn't recommend using localStorage. Please consider changing this approach. 
The changes you made messed up the layout of the Activity Card Container component. Please fix it. 
Also, we have decided to use the axios library, but you are currently using fetch.

**Comment by 1992tw** [comment]
Thanks for the input! @vitaliipp  I focused on getting things rolling fast. I added some padding to the Activity card; I thought that would look better, but we can change it if you don't like it. Quick question: What's your take on why localStorage might not be a good fit, and why the preference for Axios over fetch for our project? Let's sync up to make sure we're on the same page and loop in the mentors to align. Appreciate your thoughts!

@benochi

**Comment by vitaliipp** [comment]
If an attacker can run JavaScript on our website, they can retrieve all the data stored in local storage and send it to their own domain. This means that anything sensitive stored in local storage, such as user tokens, can be compromised. We discussed these concerns a week ago at the weekly meeting.

Just yesterday, during the meeting, the frontend team decided to use the Axios library for all requests to the backend. If you disagree, why didn't you mention this earlier?

**Review by benochi — APPROVED** [review]

**Comment by 1992tw** [comment]
Done and ready to be merged! 
@vitaliipp @benochi 

image

**Pull request merged**
