### PR TITLE
Login page integrated with backend

### PR DESCRIPTION
**Pull request by Kremifany**

### CODE REVIEW

**Review by benochi — APPROVED** [review]

**Review by oxangyal — APPROVED** [review]
LGTM

**Comment by TammamWafai** [comment]
Good job. It works, but this functionality was implemented in another PR.

**Review by 1992tw — APPROVED** [review]
Good job! 
You can merge it as it fixes some issues that I missed in my PR.

**Comment by Kremifany** [comment]
Closing as duplicate

**Pull request closed without merging**
